#!/usr/bin/env bash

read pct name thispid< <(top -l 2 -n 1 -F -o cpu -stats cpu,command,pid | tail -1)
if (( ${pct%.*} >= 50 )); then
  osascript -e 'display notification "Process > 50%: '"$name"' ('"$pct"'%) (pid: '"$thispid"')" with title "High Usage of CPU"'
fi
